// This file serves as an index for generated protobuf message types
// Generated by buf generate command from .proto files

// Re-export all generated proto types
// These will be auto-generated by: buf generate

declare global {
  namespace proto {
    namespace player {
      namespace ext {
        namespace v1 {
          class UpdatePlayerRequest {
            serializeBinary(): Uint8Array
            toObject(): Record<string, any>
            static deserializeBinary(bytes: Uint8Array): UpdatePlayerRequest
            static name: string
          }

          class UpdatePlayerResponse {
            serializeBinary(): Uint8Array
            toObject(): Record<string, any>
            static deserializeBinary(bytes: Uint8Array): UpdatePlayerResponse
            static name: string
          }

          class GetPlayerResponse {
            serializeBinary(): Uint8Array
            toObject(): Record<string, any>
            static deserializeBinary(bytes: Uint8Array): GetPlayerResponse
            static name: string
          }

          class Player {
            serializeBinary(): Uint8Array
            toObject(): Record<string, any>
            static deserializeBinary(bytes: Uint8Array): Player
            static name: string
          }
        }
      }
    }

    namespace wallet {
      namespace ext {
        namespace v1 {
          class GetWalletResponse {
            serializeBinary(): Uint8Array
            toObject(): Record<string, any>
            static deserializeBinary(bytes: Uint8Array): GetWalletResponse
            static name: string
          }

          class Wallet {
            serializeBinary(): Uint8Array
            toObject(): Record<string, any>
            static deserializeBinary(bytes: Uint8Array): Wallet
            static name: string
          }
        }
      }
    }

    namespace friends {
      namespace ext {
        namespace v1 {
          class GetFriendListResponse {
            serializeBinary(): Uint8Array
            toObject(): Record<string, any>
            static deserializeBinary(bytes: Uint8Array): GetFriendListResponse
            static name: string
          }

          class Friend {
            serializeBinary(): Uint8Array
            toObject(): Record<string, any>
            static deserializeBinary(bytes: Uint8Array): Friend
            static name: string
          }
        }
      }
    }

    namespace tournament {
      namespace ext {
        namespace v1 {
          class GetTournamentResponse {
            serializeBinary(): Uint8Array
            toObject(): Record<string, any>
            static deserializeBinary(bytes: Uint8Array): GetTournamentResponse
            static name: string
          }

          class Tournament {
            serializeBinary(): Uint8Array
            toObject(): Record<string, any>
            static deserializeBinary(bytes: Uint8Array): Tournament
            static name: string
          }
        }
      }
    }

    namespace google {
      namespace rpc {
        class Status {
          serializeBinary(): Uint8Array
          toObject(): Record<string, any>
          static deserializeBinary(bytes: Uint8Array): Status
          getCode(): number
          getMessage(): string
          getDetailsList(): any[]
        }
      }
    }
  }
}

export {}
